### PR TITLE
Allow client to pass in custom headers

### PR DESCRIPTION
**Pull request by Buktoria**
This pr allows users to pass in custom headers they may need to HTTP requests for Azkaban.

### CODE REVIEW

**Review by axelsteingrimsson — APPROVED** [review]
Looks good 👌

**Comment by axelsteingrimsson** [comment]
Actually you also need to add it to upload/delete projects

**Comment by Buktoria** [comment]
@axelsteingrimsson Updated

**Review by axelsteingrimsson — APPROVED** [review]
Perfect :)

**Comment by dterror-zz** [comment]
headers being `nil` is ok for the underlying http client? (no `no-method-defined for NilClass` drama)?

**Comment by axelsteingrimsson** [comment]
If you look at the actual underlying GET/POST methods they are passing `nil` headers in anyway. All we are doing here is exposing it to the API.

**Comment by axelsteingrimsson** [comment]
The only problem that I foresee with this is that Alysha was using HTTPPARTY in her PR and here we are using something different. But like they're request headers so it shouldn't matter right?

**Comment by Buktoria** [comment]
In theory, it should be fine to just take the headers and pass them in like this. What we can do is test this locally in longboat using this branch as the Azkaban gem to make sure everything works.

**Review by dterror-zz — APPROVED** [review]
👍 to `nil` then.

@Buktoria I think that would be a faster feedback loop, but your call

**Pull request merged**
